required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/kube-openapi/cmd/openapi-gen"
]

ignored = [
  "github.com/spf13/afero/sftp"
]

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.0-rc.1" # TODO

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.0-rc.1" # TODO

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.14.0-rc.1" # TODO

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.0-rc.1" # TODO

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.14.0-rc.1" # TODO

[[override]]
  name = "k8s.io/cluster-bootstrap"
  version = "kubernetes-1.14.0-rc.1" # TODO

[[override]]
  name = "k8s.io/component-base"
  version = "kubernetes-1.14.0-rc.1" # TODO

[[override]]
  name = "k8s.io/kube-aggregator"
  version = "kubernetes-1.14.0-rc.1" # TODO

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.14.0-rc.1" # TODO

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "15615b16d372105f0c69ff47dfe7402926a65aaa" # kubernetes-1.14.0-rc.1 # TODO

[[override]]
  name = "k8s.io/klog"
  version = "v0.1.0"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "0.1.10"

[[override]]
  name = "github.com/jmespath/go-jmespath"
  revision = "c2b33e84"

[[override]]
  name = "github.com/coreos/etcd"
  version = "3.3.10"

[[override]]
  name = "cloud.google.com/go"
  version = "0.18.0"

[[constraint]]
  name = "github.com/aliyun/alibaba-cloud-sdk-go"
  version = "1.49.2"

[[constraint]]
  name = "github.com/gardener/machine-controller-manager"
  version = "0.14.0"

[[constraint]]
  name = "k8s.io/helm"
  version = "v2.7.2"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "~1.12.48"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "^0.0.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.0.4"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "~1.4.0"

[[constraint]]
  name = "github.com/robfig/cron"
  revision = "2315d5715e36303a941d907f038da7f7c44c773b"

# use the same version that is referenced by k8s.io/apiserver
[[override]]
  name = "github.com/evanphx/json-patch"
  revision = "5858425f75500d40c52783dce87d085a483ce135"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  revision = "3d5d8f294aa03d8e98859feac328afbdf1ae0703"

[[constraint]]
  name = "github.com/pkg/errors"
  revision = "816c9085562cd7ee03e7f8188a1cfd942858cded"

# Dependencies for testing purposes only
[[constraint]]
  name = "github.com/onsi/gomega"
  version = "~1.3.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "~1.4.0"

[[constraint]]
  name = "github.com/miekg/dns"
  version = "1.0.15"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.2.0"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false

  [[prune.project]]
    name = "k8s.io/kube-openapi"
    unused-packages = false
    non-go = false
